import type { Metadata } from 'next'

import { mergeOpenGraph } from './mergeOpenGraph'

type PageMetaInput = {
  title: string
  description: string
  /** Pathname for canonical, e.g. "/brands" or "/blog/foo". */
  path: string
  /** Eyebrow tag rendered onto the OG image, e.g. "For Brands". */
  ogTag?: string
}

/**
 * Build the `Metadata` block for a page in one call. Sets canonical,
 * OpenGraph (title/description/url/og image generated by /og), and
 * matching twitter card. Root layout's `title.template` adds " | Bloom"
 * to the browser tab title — pass just the page name as `title`.
 */
export function pageMetadata({ title, description, path, ogTag }: PageMetaInput): Metadata {
  const ogImage =
    `/og?title=${encodeURIComponent(title)}` +
    `&description=${encodeURIComponent(description)}` +
    (ogTag ? `&tag=${encodeURIComponent(ogTag)}` : '')

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: mergeOpenGraph({
      title: `${title} | Bloom`,
      description,
      url: path,
      images: [{ url: ogImage, width: 1200, height: 630, alt: `Bloom · ${title}` }],
    }),
    twitter: {
      card: 'summary_large_image',
      title: `${title} | Bloom`,
      description,
    },
  }
}
