/* Generated by Proofly React Export */
import * as React from "react";

export type AccessformVariant = "Default" | "Loading" | "Disabled" | "Success" | "Error";
export interface AccessformProps {
  variant?: AccessformVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", AccessformVariant>>;
}

declare const accessform: React.ComponentType<accessformProps>;
export default accessform;
