/* Generated by Proofly React Export */
import * as React from "react";

export type AccordionVariant = "Closed" | "Open" | "last-closed" | "last-open";
export interface AccordionProps {
  variant?: AccordionVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", AccordionVariant>>;
  question?: string;
  answer?: string;
  click?: (...args: any[]) => void;
  backgroundColor?: string;
  textColor?: string;
}

declare const Accordion: React.ComponentType<AccordionProps>;
export default Accordion;
