/* Generated by Proofly React Export */
import * as React from "react";

export interface animationtreeProps {
  vectorColor?: string;
  strokeWidth?: number;
}

declare const animationtree: React.ComponentType<animationtreeProps>;
export default animationtree;
