/* Generated by Proofly React Export */
import * as React from "react";

export type AnimationmapVariant = "Variant 1" | "Variant 2" | "Variant 3" | "Variant 4";
export interface AnimationmapProps {
  variant?: AnimationmapVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", AnimationmapVariant>>;
}

declare const animationmap: React.ComponentType<animationmapProps>;
export default animationmap;
