/* Generated by Proofly React Export */
import * as React from "react";

export interface animationwebProps {
  vectorColor?: string;
  strokeWidth?: number;
}

declare const animationweb: React.ComponentType<animationwebProps>;
export default animationweb;
