/* Generated by Proofly React Export */
import * as React from "react";

export type AnimationproductsVariant = "Variant 1" | "Variant 2";
export interface AnimationproductsProps {
  variant?: AnimationproductsVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", AnimationproductsVariant>>;
  image1?: string | { src: string; srcSet?: string; alt?: string };
  image2?: string | { src: string; srcSet?: string; alt?: string };
  image3?: string | { src: string; srcSet?: string; alt?: string };
  image4?: string | { src: string; srcSet?: string; alt?: string };
}

declare const animationproducts: React.ComponentType<animationproductsProps>;
export default animationproducts;
