/* Generated by Proofly React Export */
import * as React from "react";

export interface BlogCardProps {
  image?: string | { src: string; srcSet?: string; alt?: string };
  title?: string;
  authorImage?: string | { src: string; srcSet?: string; alt?: string };
  authorName?: string;
  link?: string;
}

declare const BlogCard: React.ComponentType<BlogCardProps>;
export default BlogCard;
