/* Generated by Proofly React Export */
import * as React from "react";

export type BlogCard2Variant = "desktop" | "tablet" | "phone";
export interface BlogCard2Props {
  variant?: BlogCard2Variant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", BlogCard2Variant>>;
  image?: string | { src: string; srcSet?: string; alt?: string };
  title?: string;
  link?: string;
  date?: string;
}

declare const BlogCard2: React.ComponentType<BlogCard2Props>;
export default BlogCard2;
