/* Generated by Proofly React Export */
import * as React from "react";

export interface BlogPrototypeProps {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const BlogPrototype: React.ComponentType<BlogPrototypeProps>;
export default BlogPrototype;
