/* Generated by Proofly React Export */
import * as React from "react";

export interface brandssliderProps {
  children?: any[];
  speed?: number;
  direction?: "Left" | "Right" | "Top" | "Bottom";
  align?: "flex-start" | "center" | "flex-end";
  gap?: number;
  padding?: number;
  sizing?: Record<string, any>;
  clipping?: Record<string, any>;
  hover?: number;
}

declare const brandsslider: React.ComponentType<brandssliderProps>;
export default brandsslider;
