/* Generated by Proofly React Export */
import * as React from "react";

export interface brandsintroanimationProps {
  vectorColor?: string;
  strokeWidth?: number;
}

declare const brandsintroanimation: React.ComponentType<brandsintroanimationProps>;
export default brandsintroanimation;
