/* Generated by Proofly React Export */
import * as React from "react";

export interface ButtonProps {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const Button: React.ComponentType<ButtonProps>;
export default Button;
