/* Generated by Proofly React Export */
import * as React from "react";

export type Button4Variant = "Default" | "Loading" | "Disabled" | "Success" | "Error";
export interface Button4Props {
  variant?: Button4Variant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", Button4Variant>>;
}

declare const Button4: React.ComponentType<Button4Props>;
export default Button4;
