/* Generated by Proofly React Export */
import * as React from "react";

export type Button3Variant = "Default" | "Loading" | "Disabled" | "Success" | "Error";
export interface Button3Props {
  variant?: Button3Variant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", Button3Variant>>;
}

declare const Button3: React.ComponentType<Button3Props>;
export default Button3;
