/* Generated by Proofly React Export */
import * as React from "react";

export type EmailbuttonVariant = "default" | "small";
export interface EmailbuttonProps {
  variant?: EmailbuttonVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", EmailbuttonVariant>>;
  sendEmail?: (...args: any[]) => void;
  backgroundColor?: string;
  textColor?: string;
}

declare const emailbutton: React.ComponentType<emailbuttonProps>;
export default emailbutton;
