/* Generated by Proofly React Export */
import * as React from "react";

export interface FAQAccordionProps {
  select?: any;
  name?: any;
  name?: any;
  mirrored?: any;
  color?: any;
}

declare const FAQAccordion: React.ComponentType<FAQAccordionProps>;
export default FAQAccordion;
