/* Generated by Proofly React Export */
import * as React from "react";

export type FaqbrandsVariant = "Closed" | "Open" | "last-closed" | "last-open";
export interface FaqbrandsProps {
  variant?: FaqbrandsVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", FaqbrandsVariant>>;
  question?: string;
  answer?: string;
  click?: (...args: any[]) => void;
  backgroundColor?: string;
  textColor?: string;
}

declare const faqbrands: React.ComponentType<faqbrandsProps>;
export default faqbrands;
