/* Generated by Proofly React Export */
import * as React from "react";

export interface FAQPrototypeProps {
  select?: any;
  name?: any;
  name?: any;
  mirrored?: any;
  color?: any;
}

declare const FAQPrototype: React.ComponentType<FAQPrototypeProps>;
export default FAQPrototype;
