/* Generated by Proofly React Export */
import * as React from "react";

export type FaqprovidersVariant = "Closed" | "Open" | "last-closed" | "last-open";
export interface FaqprovidersProps {
  variant?: FaqprovidersVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", FaqprovidersVariant>>;
  question?: string;
  answer?: string;
  click?: (...args: any[]) => void;
  backgroundColor?: string;
  textColor?: string;
}

declare const faqproviders: React.ComponentType<faqprovidersProps>;
export default faqproviders;
