/* Generated by Proofly React Export */
import * as React from "react";

export type FooterVariant = "Desktop" | "Tablet" | "Phone" | "Laptop";
export interface FooterProps {
  variant?: FooterVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", FooterVariant>>;
}

declare const Footer: React.ComponentType<FooterProps>;
export default Footer;
