/* Generated by Proofly React Export */
import * as React from "react";

export type ImagecardnobuttonVariant = "DESK img at right" | "DESK img at left" | "PHONE";
export interface ImagecardnobuttonProps {
  variant?: ImagecardnobuttonVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", ImagecardnobuttonVariant>>;
  heading?: string;
  text?: string;
  image?: string | { src: string; srcSet?: string; alt?: string };
  spamTitle?: string;
  spanTitleColor?: string;
}

declare const imagecardnobutton: React.ComponentType<imagecardnobuttonProps>;
export default imagecardnobutton;
