/* Generated by Proofly React Export */
import * as React from "react";

export interface imagecardbuttonProps {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const imagecardbutton: React.ComponentType<imagecardbuttonProps>;
export default imagecardbutton;
