/* Generated by Proofly React Export */
import * as React from "react";

export type ImputsliderVariant = "Variant 1" | "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12" | "13" | "14";
export interface ImputsliderProps {
  variant?: ImputsliderVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", ImputsliderVariant>>;
}

declare const imputslider: React.ComponentType<imputsliderProps>;
export default imputslider;
