/* Generated by Proofly React Export */
import * as React from "react";

/** This component has no customizable props — it's a pre-composed design component. */

declare const InputBox: React.ComponentType<Record<string, any>> & {
  Responsive: React.ComponentType<Record<string, any>>;
};
export default InputBox;
