/* Generated by Proofly React Export */
import * as React from "react";

export interface leadershipcardProps {
  name?: string;
  role?: string;
  picture?: string | { src: string; srcSet?: string; alt?: string };
  click?: (...args: any[]) => void;
}

declare const leadershipcard: React.ComponentType<leadershipcardProps>;
export default leadershipcard;
