/* Generated by Proofly React Export */
import * as React from "react";

export interface leadershipcardtextProps {
  click?: (...args: any[]) => void;
}

declare const leadershipcardtext: React.ComponentType<leadershipcardtextProps>;
export default leadershipcardtext;
