/* Generated by Proofly React Export */
import * as React from "react";

export type LoadMoreVariant = "Default" | "Loading" | "Hidden";
export interface LoadMoreProps {
  variant?: LoadMoreVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", LoadMoreVariant>>;
  click?: (...args: any[]) => void;
}

declare const LoadMore: React.ComponentType<LoadMoreProps>;
export default LoadMore;
