/* Generated by Proofly React Export */
import * as React from "react";

export type LoadMoreButtonVariant = "Default" | "Loading" | "Hidden";
export interface LoadMoreButtonProps {
  variant?: LoadMoreButtonVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", LoadMoreButtonVariant>>;
  click?: (...args: any[]) => void;
}

declare const LoadMoreButton: React.ComponentType<LoadMoreButtonProps>;
export default LoadMoreButton;
