/* Generated by Proofly React Export */
import * as React from "react";

export interface mockuptermsProps {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const mockupterms: React.ComponentType<mockuptermsProps>;
export default mockupterms;
