/* Generated by Proofly React Export */
import * as React from "react";

export interface NavigationProps {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const Navigation: React.ComponentType<NavigationProps>;
export default Navigation;
