/* Generated by Proofly React Export */
import * as React from "react";

export type NavigationLinkVariant = "Default" | "Variant 2";
export interface NavigationLinkProps {
  variant?: NavigationLinkVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", NavigationLinkVariant>>;
  title?: string;
  link?: string;
}

declare const NavigationLink: React.ComponentType<NavigationLinkProps>;
export default NavigationLink;
