/* Generated by Proofly React Export */
import * as React from "react";

export type NavigationTopbarVariant = "Menu" | "Close";
export interface NavigationTopbarProps {
  variant?: NavigationTopbarVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", NavigationTopbarVariant>>;
  tap?: (...args: any[]) => void;
}

declare const NavigationTopbar: React.ComponentType<NavigationTopbarProps>;
export default NavigationTopbar;
