/* Generated by Proofly React Export */
import * as React from "react";

export type NavigationMenuIconVariant = "Menu" | "Close";
export interface NavigationMenuIconProps {
  variant?: NavigationMenuIconVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", NavigationMenuIconVariant>>;
  tap?: (...args: any[]) => void;
}

declare const NavigationMenuIcon: React.ComponentType<NavigationMenuIconProps>;
export default NavigationMenuIcon;
