/* Generated by Proofly React Export */
import * as React from "react";

export interface Navigation2Props {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const Navigation2: React.ComponentType<Navigation2Props>;
export default Navigation2;
