/* Generated by Proofly React Export */
import * as React from "react";

export type NavigationMenuVariant = "Default" | "Variant 2";
export interface NavigationMenuProps {
  variant?: NavigationMenuVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", NavigationMenuVariant>>;
  title?: string;
  link?: string;
}

declare const NavigationMenu: React.ComponentType<NavigationMenuProps>;
export default NavigationMenu;
