/* Generated by Proofly React Export */
import * as React from "react";

export type NEWSCARDVariant = "Variant 1" | "tablet" | "phone";
export interface NEWSCARDProps {
  variant?: NEWSCARDVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", NEWSCARDVariant>>;
  link?: string;
  image?: string | { src: string; srcSet?: string; alt?: string };
  text?: string;
  date?: string;
  logo?: string | { src: string; srcSet?: string; alt?: string };
}

declare const NEWSCARD: React.ComponentType<NEWSCARDProps>;
export default NEWSCARD;
