/* Generated by Proofly React Export */
import * as React from "react";

export type PillarscontentVariant = "build" | "deliver" | "service" | "phone-network" | "phone-build" | "phone-deliver" | "phone-service";
export interface PillarscontentProps {
  variant?: PillarscontentVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", PillarscontentVariant>>;
}

declare const pillarscontent: React.ComponentType<pillarscontentProps>;
export default pillarscontent;
