/* Generated by Proofly React Export */
import * as React from "react";

export interface pillarsProps {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const pillars: React.ComponentType<pillarsProps>;
export default pillars;
