/* Generated by Proofly React Export */
import * as React from "react";

export interface PricingFeaturesProps {
  select?: any;
  name?: any;
  name?: any;
  mirrored?: any;
  color?: any;
  style?: any;
}

declare const PricingFeatures: React.ComponentType<PricingFeaturesProps>;
export default PricingFeatures;
