/* Generated by Proofly React Export */
import * as React from "react";

export type PricingmatrixVariant = "gradient" | "single color";
export interface PricingmatrixProps {
  variant?: PricingmatrixVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", PricingmatrixVariant>>;
  color?: string;
}

declare const pricingmatrix: React.ComponentType<pricingmatrixProps>;
export default pricingmatrix;
