/* Generated by Proofly React Export */
import * as React from "react";

export interface PricingCardProps {
  select?: any;
  name?: any;
  name?: any;
  mirrored?: any;
  color?: any;
  style?: any;
}

declare const PricingCard: React.ComponentType<PricingCardProps>;
export default PricingCard;
