/* Generated by Proofly React Export */
import * as React from "react";

export interface prompt2Props {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const prompt2: React.ComponentType<prompt2Props>;
export default prompt2;
