/* Generated by Proofly React Export */
import * as React from "react";

export type RowVariant = "Closed" | "Open" | "last-closed" | "last-open";
export interface RowProps {
  variant?: RowVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", RowVariant>>;
  question?: string;
  answer?: string;
  click?: (...args: any[]) => void;
  backgroundColor?: string;
  textColor?: string;
}

declare const Row: React.ComponentType<RowProps>;
export default Row;
