/* Generated by Proofly React Export */
import * as React from "react";

export type ScrolldownVariant = "default" | "small";
export interface ScrolldownProps {
  variant?: ScrolldownVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", ScrolldownVariant>>;
  text?: string;
  icon?: string | { src: string; srcSet?: string; alt?: string };
  textColor?: string;
  link?: string;
}

declare const scrolldown: React.ComponentType<scrolldownProps>;
export default scrolldown;
