/* Generated by Proofly React Export */
import * as React from "react";

export interface SECTIONHERONEWProps {
  placeholder?: string;
  placeholderColor?: string;
  textColor?: string;
  font?: any;
  fontSize?: number;
  textareaBG?: string;
  borderColor?: string;
  radius?: number;
  buttonBG?: string;
  buttonTextColor?: string;
  height?: number;
}

declare const SECTIONHERONEW: React.ComponentType<SECTIONHERONEWProps>;
export default SECTIONHERONEW;
