/* Generated by Proofly React Export */
import * as React from "react";

export interface SECTIONHEROTEMPProps {
  placeholder?: string;
  placeholderColor?: string;
  textColor?: string;
  font?: any;
  fontSize?: number;
  textareaBG?: string;
  borderColor?: string;
  radius?: number;
  buttonBG?: string;
  buttonTextColor?: string;
  height?: number;
}

declare const SECTIONHEROTEMP: React.ComponentType<SECTIONHEROTEMPProps>;
export default SECTIONHEROTEMP;
