/* Generated by Proofly React Export */
import * as React from "react";

export interface SECTIONleadershipProps {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const SECTIONleadership: React.ComponentType<SECTIONleadershipProps>;
export default SECTIONleadership;
