/* Generated by Proofly React Export */
import * as React from "react";

export interface sendButtonProps {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const sendButton: React.ComponentType<sendButtonProps>;
export default sendButton;
