/* Generated by Proofly React Export */
import * as React from "react";

export type SeplineVariant = "gradient" | "single color";
export interface SeplineProps {
  variant?: SeplineVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", SeplineVariant>>;
  color?: string;
}

declare const sepline: React.ComponentType<seplineProps>;
export default sepline;
