/* Generated by Proofly React Export */
import * as React from "react";

export interface socialproofProps {
  select?: any;
  name?: any;
  name?: any;
  mirrored?: any;
  color?: any;
  style?: any;
}

declare const socialproof: React.ComponentType<socialproofProps>;
export default socialproof;
