/* Generated by Proofly React Export */
import * as React from "react";

export interface socialproofsectionProps {
  children?: any;
  direction?: any;
  align?: any;
  gap?: any;
  sizing?: any;
  snapping?: any;
  fading?: any;
  progress?: any;
  arrows?: any;
  ariaLabel?: any;
  radius?: any;
}

declare const socialproofsection: React.ComponentType<socialproofsectionProps>;
export default socialproofsection;
