/* Generated by Proofly React Export */
import * as React from "react";

export interface socialproofsection2Props {
  children?: any;
  direction?: any;
  align?: any;
  gap?: any;
  sizing?: any;
  snapping?: any;
  fading?: any;
  progress?: any;
  arrows?: any;
  ariaLabel?: any;
  radius?: any;
}

declare const socialproofsection2: React.ComponentType<socialproofsection2Props>;
export default socialproofsection2;
