/* Generated by Proofly React Export */
import * as React from "react";

export type StepssliderVariant = "Variant 1" | "Variant 2" | "Variant 3" | "Variant 4" | "Variant 5" | "Variant 6" | "Variant 7" | "Variant 8" | "PHONE";
export interface StepssliderProps {
  variant?: StepssliderVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", StepssliderVariant>>;
}

declare const stepsslider: React.ComponentType<stepssliderProps>;
export default stepsslider;
