/* Generated by Proofly React Export */
import * as React from "react";

export type Storiescard_2Variant = "right" | "left" | "LIL - right" | "phone - bottom" | "LIL - left" | "phone - top";
export interface Storiescard_2Props {
  variant?: Storiescard_2Variant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", Storiescard_2Variant>>;
  background?: string;
  text?: string;
  textColor?: string;
  background?: string | { src: string; srcSet?: string; alt?: string };
  logo?: string | { src: string; srcSet?: string; alt?: string };
  link?: string;
}

declare const storiescard: React.ComponentType<storiescardProps>;
export default storiescard;
