/* Generated by Proofly React Export */
import * as React from "react";

export type StoriescardVariant = "Variant 1" | "Variant 2";
export interface StoriescardProps {
  variant?: StoriescardVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", StoriescardVariant>>;
  background?: string;
  image?: string | { src: string; srcSet?: string; alt?: string };
}

declare const storiescard: React.ComponentType<storiescardProps>;
export default storiescard;
