/* Generated by Proofly React Export */
import * as React from "react";

export type TabVariant = "Disable" | "Active" | "Disable v2" | "Active v2";
export interface TabProps {
  variant?: TabVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", TabVariant>>;
  title?: string;
  click?: (...args: any[]) => void;
  radius?: any;
}

declare const Tab: React.ComponentType<TabProps>;
export default Tab;
