/* Generated by Proofly React Export */
import * as React from "react";

export interface teammembercardProps {
  stroke?: string;
  width?: number;
  dots?: number;
}

declare const teammembercard: React.ComponentType<teammembercardProps>;
export default teammembercard;
