/* Generated by Proofly React Export */
import * as React from "react";

export interface TestimonialCopyProps {
  select?: any;
  name?: any;
  name?: any;
  mirrored?: any;
  color?: any;
  style?: any;
}

declare const TestimonialCopy: React.ComponentType<TestimonialCopyProps>;
export default TestimonialCopy;
