/* Generated by Proofly React Export */
import * as React from "react";

export type TokenVariant = "Mobility Brand" | "Service Provider" | "phone - mobility brand" | "phone - service provider";
export interface TokenProps {
  variant?: TokenVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", TokenVariant>>;
}

declare const token: React.ComponentType<tokenProps>;
export default token;
