/* Generated by Proofly React Export */
import * as React from "react";

export type WehelpmakeVariant = "Variant 1" | "Variant 2" | "Variant 3" | "Variant 4" | "phone 1" | "phone 2" | "phone 3" | "phone 4";
export interface WehelpmakeProps {
  variant?: WehelpmakeVariant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", WehelpmakeVariant>>;
  color1?: string;
  color2?: string;
}

declare const wehelpmake: React.ComponentType<wehelpmakeProps>;
export default wehelpmake;
