/* Generated by Proofly React Export */
import * as React from "react";

export type Wehelpmake2Variant = "Variant 1" | "Variant 2" | "Variant 3" | "Variant 4" | "phone 1" | "phone 2" | "phone 3" | "phone 4";
export interface Wehelpmake2Props {
  variant?: Wehelpmake2Variant | Partial<Record<"base" | "sm" | "md" | "lg" | "xl", Wehelpmake2Variant>>;
  color1?: string;
  color2?: string;
}

declare const wehelpmake2: React.ComponentType<wehelpmake2Props>;
export default wehelpmake2;
